- src/api/admin.py
- src/api/models.py
--Models: Add models User, Jobs and Client
--Admin: Add in admin User, Jobs and Client
> [Add models]

- src/api/admin.py
- src/api/models.py
Add methods serialize, repr, save, update and delete from Client and Job
> Add models

- src/api/admin.py
- src/api/models.py
- src/app.py
--Models: Add phone and fix db.session.commit
--App: Add Get User, get all users, get user by username and post user
> [Add API Gets User and Post User]

- Pipfile
- Pipfile.lock
> Encriptado de Contraseñas

- src/app.py
--Add methods API put and delete User
--Fix getUserById return the phone
> [Add methods PUT y DELETE User]

- Pipfile
- Pipfile.lock
- src/api/models.py
- src/app.py
Missing save Token in localStorage
Couldn't test it because I could't access the admi
> Added the login's methods POST and GET for /protected

- Pipfile
- Pipfile.lock
- src/api/models.py
- src/app.py
Added Client's methods GetClients, GetClient, Post, Put, Delete
Tested on POSTMAN and working
> Api client

- src/api/models.py
- src/app.py
--Add method get all jobs in the api
> [Add Get Job]

- src/app.py
--Cambio a comillas simples en los métodos
> [Fix Comillas]

- src/app.py
Fixed some errors on the GET method of /protected
Added the user properties
> Fix /protected method

- src/front/js/component/cardInformation.js
- src/front/js/component/cardOffers.js
- src/front/js/component/cardProducts.js
- src/front/js/component/cardSearchCode.js
- src/front/js/pages/home.js
- src/front/styles/home.css
> Add-home-front-end

- Pipfile
- src/api/models.py
- src/app.py
- src/front/js/store/appContext.js
- src/front/js/store/flux.js
--Pipfile Add Ptyz
--Models Add timezone Costa Rica
--flux y appContext Post Jobs
--App add methods Api for Jobs
> Add api jobs

- Pipfile.lock
- package-lock.json
- package.json
- src/front/js/component/cardSearchCode.js
- src/front/js/component/clientsButtons.js
- src/front/js/component/clientsModal.js
- src/front/js/component/clientsTable.js
- src/front/js/component/clientsTableHeader.js
- src/front/js/component/usersButtons.js
- src/front/js/component/usersModal.js
- src/front/js/component/usersTable.js
- src/front/js/component/usersTableHeader.js
- src/front/js/layout.js
- src/front/js/pages/changePass.js
- src/front/js/pages/fotgotPass.js
- src/front/js/pages/login.js
- src/front/js/pages/users.js
- src/front/styles/changePass.css
- src/front/styles/forgotPass.css
- src/front/styles/home.css
- src/front/styles/login.css
- src/front/styles/users.css
[Added Users Front End and fixed some errors regarding form-control classNames in Yahaira's Views and Amanda's components, additionally I corrected some clasesNames on ClientsFrontEnd]
> Added UsersFrontEnd

- package.json
- src/api/models.py
- src/front/js/component/navbar.js
- src/front/js/layout.js
- src/front/js/pages/login.js
- src/front/js/store/appContext.js
- src/front/js/store/flux.js
--Add endpoints gor getall users,clients, jobs
> Fix hidden buttons

- src/front/js/component/footer.js
- src/front/js/component/navbar.js
- src/front/js/component/usersTable.js
- src/front/js/layout.js
- src/front/js/pages/changePass.js
- src/front/js/pages/fotgotPass.js
- src/front/js/pages/home.js
- src/front/js/pages/login.js
- src/front/js/pages/users.js
- src/front/js/store/appContext.js
- src/front/js/store/flux.js
--Fix Navbar and footer hidden items
--Fix Error navigate
--Add map users
> [Add Map to User]

- src/app.py
- src/front/js/component/usersButtons.js
- src/front/js/component/usersModal.js
- src/front/js/component/usersTable.js
- src/front/js/pages/fotgotPass.js
- src/front/js/pages/users.js
- src/front/js/store/appContext.js
- src/front/js/store/flux.js
- src/front/styles/forgotPass.css
- src/front/styles/users.css
--Fix Api check empty in body request
--Add Endpoint for add, update and delete users
--Add search input by id, firstname, lastname, role
> [Add addEndpointsUser]

- src/app.py
- src/front/js/component/clientsButtons.js
- src/front/js/component/clientsModal.js
- src/front/js/component/clientsTable.js
- src/front/js/component/footer.js
- src/front/js/component/navbar.js
- src/front/js/component/usersButtons.js
- src/front/js/component/usersModal.js
- src/front/js/component/usersTable.js
- src/front/js/component/usersTableHeader.js
- src/front/js/pages/clients.js
- src/front/js/store/flux.js
--Add endpoints for add and unpdate clients
--Add search client by id, firstname and lastname
> [Add endpoints clients]

- src/front/js/component/clientsModal.js
- src/front/js/component/footer.js
- src/front/js/component/navbar.js
- src/front/js/component/usersButtons.js
- src/front/js/component/usersModal.js
- src/front/js/pages/aboutUs.js
- src/front/js/pages/ourServices.js
- src/front/js/store/flux.js
- src/front/styles/ourServices.css
--Fix margin ourServices
--Add my jobs to navbar and footer
> [Fix fixSomeError]

- src/front/js/component/cardSearchCode.js
- src/front/js/store/flux.js
- template.html
[Added a swal for the front end status]
> StatusCodeFrontEnd

- Pipfile
- src/app.py
- src/front/js/component/clientsButtons.js
- src/front/js/component/clientsTable.js
- src/front/js/component/clientsTableHeader.js
- src/front/js/component/jobsAdmiTable.js
- src/front/js/component/jobsTechnicalTable.js
- src/front/js/component/navbar.js
- src/front/js/component/usersButtons.js
- src/front/js/component/usersTable.js
- src/front/js/component/usersTableHeader.js
- src/front/js/pages/changePass.js
- src/front/js/pages/fotgotPass.js
- src/front/js/pages/login.js
- src/front/js/store/flux.js
- src/front/styles/backToTopBtn.css
- src/front/styles/changePass.css
- src/front/styles/contactUs.css
- src/front/styles/forgotPass.css
- src/front/styles/index.css
- src/front/styles/jobsAdmi.css
- src/front/styles/jobsTechnical.css
- src/front/styles/login.css
- src/front/styles/users.css
--Add function for clear store of variables for inputs --Fix some error of font
--Fix check if client exists
--Fix delete user if have a job assign
> [Add clear store function]

- src/api/models.py
- src/app.py
- src/front/js/component/footer.js
- src/front/js/component/jobsAdmiTable.js
- src/front/js/component/jobsAdmiTableHeader.js
- src/front/js/store/flux.js
--Fix delete user when have a job assign
> [fixDeleteUser]

- src/api/models.py
- src/app.py
- src/front/js/component/clientsModal.js
- src/front/js/component/jobsAdmiButtons.js
- src/front/js/component/jobsAdmiModal.js
- src/front/js/component/jobsAdmiTable.js
- src/front/js/component/jobsAdmiTableHeader.js
- src/front/js/component/jobsTechnicalModal.js
- src/front/js/component/jobsTechnicalTable.js
- src/front/js/component/jobsTechnicalTableHeader.js
- src/front/js/component/usersModal.js
- src/front/js/layout.js
- src/front/js/store/flux.js
- src/front/js/utils/privateRoutes.js
- src/front/styles/jobsAdmi.css
- src/front/styles/jobsTechnical.css
- src/front/styles/users.css
--Add button message whatsapp
--Fix close button modal clear fields
--Fix validation routes by role(admin, technical)
> [Add button message]

- package.json
- src/front/js/component/mapLocation.js
- src/front/js/pages/home.js
- src/front/styles/mapLocation.css
- template.html
it includes the js, css, and other modifications regarding the 3rd party API
> [Adding the 3rd party API]

- src/front/js/component/contactUsTable.js
- src/front/js/component/mapLocation.js
- src/front/js/pages/home.js
- src/front/styles/contactUs.css
- src/front/styles/mapLocation.css
[Added the map component to the Contact Us view]
> [Added the map component to the Contact Us view]

- src/app.py
Reverts 4GeeksAcademy/FinalProject-AmandaBogantes-EuniceHidalgo-YahairaCalvo-StefanyMendez#47
> Revert "jtw_required"

- src/front/js/pages/aboutUs.js
- src/front/styles/aboutUs.css
[text about us justify and change height of mission's and vission's container]
> Fixed About Us

- src/app.py
- src/front/js/component/cardSearchCode.js
- src/front/js/component/contactUsTable.js
- src/front/js/pages/aboutProject.js
- src/front/js/pages/home.js
- src/front/js/store/flux.js
- src/front/styles/home.css
- src/front/styles/index.css
--Add JWT to the flux
--Fix validation empty fields send message
--Fix image in home
> Add jwt flux

- src/front/js/pages/aboutProject.js
- src/front/styles/aboutProject.css
--Add name to photos of developers
> [Add names of developers]

- src/front/js/component/clientsTableHeader.js
- src/front/js/component/jobsTechnicalModal.js
- src/front/js/pages/aboutProject.js
- src/front/js/pages/aboutUs.js
- src/front/js/pages/ourServices.js
- src/front/styles/aboutProject.css
- src/front/styles/ourServices.css
- src/templates/contact.html
--Fix Error last name clientsTableHeader
--Fix Error margin aboutUs
> Fix error ortogra

- src/front/js/component/jobsAdmiTable.js
- src/front/js/component/jobsTechnicalTable.js
--Fix spaces in message whatsapp
> [Fix Spaces in message]
